### ISSUE TITLE
自由能形貌图2D和3D的颜色不一致

### ISSUE THREAD

**Issue by feifiredock** [CharlesHahn/DuIvyTools#2]
尊敬的作者，我是一个模拟新手，看到您的公众号和知乎发现这个工具，画自由能形貌图等等非常好用。我发现自由能形貌图2D和3D的颜色无法达成一致，即便是自由能形貌图3D版本一样好看，但对于论文的发表可能有一定影响。由于我的python绘图基础薄弱，我希望您能告诉我如何调整两个形式图中的颜色一致，或者您对自由能形貌图的工具稍做修改，非常感谢您开发的相关工具以及分享的模拟知识

**Comment by CharlesHahn** [comment]
@feifeidock 您好！
目前我暂时没有将两个图中的颜色调整至一致的想法（个人觉得不太美观），可能需要您自己调一下。平面图和3D图都是使用matplotlib默认的颜色方案绘制的，平面图使用的是jet颜色方案，而3D图使用的是coolwarm方案。
3D图的颜色方案控制cmap="coolwarm"在XPM.py的719和730行，分别是3D的底部平面图和上方3D图的颜色控制。
平面图的话，如果您未使用-pcm参数且使用了-ip，则颜色控制在523行；若使用了-pcm未使用-ip，在624行；若使用了-pcm且使用了-ip，则在638行。
您如果只是需要保持颜色一致的话，可以将这些地方的颜色方案改成一样的就行了。
具体colormap的选择可以参考https://matplotlib.org/stable/tutorials/colors/colormaps.html。
XPM模块的位置（以防您找不到），应该是在您python安装位置的Lib/site-packages/DuIvyTools/路径下。
祝好~
