### ISSUE TITLE
TypeError in XPM.py

### ISSUE THREAD

**Issue by supers1x** [CharlesHahn/DuIvyTools#3]
When I run `dit xpm_show -3d` and this error occurred:

![image](https://user-images.githubusercontent.com/8362538/219090944-2efe0d53-034c-419e-9c3e-ae82447482a0.png)

Changing the line https://github.com/CharlesHahn/DuIvyTools/blob/2eec9498f94c529eb0d0aae7db22ba431e4a0b8f/DuIvyTools/XPM.py#L663
to `ax = fig.add_subplot(projection='3d')` will solve the problem.

**Comment by CharlesHahn** [comment]
fixed in v0.4.8, thanks for your comment.
