### ISSUE TITLE
可以在xpm_show -3d 加入设定坐标轴scale的功能吗

### ISSUE THREAD

**Issue by mapuyi** [CharlesHahn/DuIvyTools#6]
xpm_show -3d目前只能默认生成x,y,z三个坐标轴等长的图，希望可以添加自己设定坐标轴范围的option。谢谢！

**Comment by CharlesHahn** [comment]
目前是可以通过xmin, xmax, ymin, ymax, zmin, zmax来调控数据在三个坐标轴的范围的，不过我想您说的应该是坐标轴的长度？后续我会试试看的。谢谢您的建议
